default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: comunit_local
  #username: test_app
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: comunit_local_test

production:
  <<: *default
  database: comunit_local
  username: comunit
  password: <%= ENV['DATABASE_PASSWORD'] %>
